stages:
  - Test
  - Deploy
  - Build

variables:
  TERM: xterm-color
  # REGISTRY_HOST: gitlab.com
  REGISTRY_NAMESPACE: mirik12mirik

Build:
  stage: Build
  tags: 
    - docker
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  variables:
    PHP_IMAGE: php:8.2-fpm-alpine
    NGINX_IMAGE: nginx:latest
    TARGET_APP: php_dev
    TARGET_PROXY: nginx_dev
    DOCKER_FILE: ${CI_PROJECT_DIR}/k8s/Dockerfile
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin 
    
    - TARGET_IMAGE="${REGISTRY_NAMESPACE}/${TARGET_APP}"
    - >
      echo "Build ${TARGET_IMAGE}:${CI_COMMIT_SHORT_SHA}" &&
      docker build -t ${TARGET_IMAGE}:${CI_COMMIT_SHORT_SHA}
      -t ${TARGET_IMAGE}:latest
      --build-arg PHP_IMAGE=$PHP_IMAGE
      --build-arg NGINX_IMAGE=$NGINX_IMAGE
      --cache-from type=registry,ref=${TARGET_IMAGE}:latest
      --cache-to type=inline
      --file "${DOCKER_FILE}"
      --target=${TARGET_APP}
      --push .

    - TARGET_IMAGE="${REGISTRY_NAMESPACE}/${TARGET_PROXY}"
    - >
      echo "Build ${TARGET_IMAGE}:${CI_COMMIT_SHORT_SHA}" &&
      docker build -t ${TARGET_IMAGE}:${CI_COMMIT_SHORT_SHA}
      -t ${TARGET_IMAGE}:latest
      --build-arg PHP_IMAGE=$PHP_IMAGE
      --build-arg NGINX_IMAGE=$NGINX_IMAGE
      --cache-from type=registry,ref=${TARGET_IMAGE}:latest
      --cache-to type=inline
      --file "${DOCKER_FILE}"
      --target=${TARGET_PROXY}
      --push .
  only:
    - main
