apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: php
  name: php
spec:
  containers:
  - image: mirik12mirik/php_dev:latest
    name: php
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
