webserver:
  ingress:
    enabled: true
    websites:
      host: "laravel-10.local"
      port: 80
  http:
    repository:
      image: mirik12mirik/nginx_dev
      pullPolicy: IfNotPresent
      tag: latest

  php:
    image: mirik12mirik/php_dev
    pullPolicy: IfNotPresent
    tag: latest

mariadb:
  enabled: true
  auth:
    database: laravel-10
  image:
    repository: bitnami.mariadb
    tag: 10.6

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
