apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-laravel10.fullname" . }}
  labels:
    {{- include "my-laravel10.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "my-laravel10.selectorLabels" . | nindent 4 }}


# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}
#   labels:
#     {{- include "my-laravel10.labels" . | nindent 4 }}
# spec:
#   type: ClusterIP
#   ports:
#     - port: 8080
#       targetPort: 8080
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "my-laravel10.selectorLabels" . | nindent 4 }}

